# -*- coding: utf-8 -*-
"""energyconsumption.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A7CSdAqqfDLXItE9hZWe-yG66zvCBB_U

IMPORTING THE DATASET
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files
uploaded = files.upload()

"""READING THE DATAS IN THE CSV FILE"""

df=pd.read_csv("PJME_hourly.csv")
print(df)

"""PRINTING THE HEADER FILES"""

print(df.head())

"""PRINTING THE BOTTOM ELEMENTS"""

print(df.tail())

"""DESCRIBING ELEMENTS"""

df.describe()

"""INFO/DATAYPES"""

df.info()

"""HISTOGRAPH"""

df.hist()

"""MEASUREMENT OF ENERGY CONSUMPTION USING DISTRIBUTION PLOT"""

df.plot(title="PJME Energy use in MegaWatts",
        figsize=(20, 8),
        style=".",
        color=sns.color_palette()[0])

"""SCATTER PLOT"""

import pandas as pd
import matplotlib.pyplot as plt

# Sample data (replace this with your actual data)
data = {
    'Datetime': ['2023-01-01 00:00', '2023-01-01 01:00', '2023-01-01 02:00', '2023-01-01 03:00'],
    'Energy_Consumption': [100, 150, 130, 180]  # Replace these values with your energy consumption data
}

# Creating a DataFrame from the sample data
df = pd.DataFrame(data)
df['Datetime'] = pd.to_datetime(df['Datetime'])  # Convert 'Datetime' column to datetime type

# Plotting the data
plt.figure(figsize=(10, 6))
plt.plot(df['Datetime'], df['Energy_Consumption'], marker='o', color='b', linestyle='-', linewidth=2, markersize=8)
plt.title('Energy Consumption Over Time')
plt.xlabel('Datetime')
plt.ylabel('Energy Consumption')
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""CONCLUSION

"""